NATIVE-553: Feature Flag: Disable Splash Screen
Integreat/integreat-react-native-app pull request #309
Opened 2020-09-01 13:32 UTC by maxammann

This pull request belongs to an issue on our [bugtracker](https://issues.integreat-app.de/).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword **NATIVE**.

2020-09-12 09:30 UTC, maxammann commented
When merging this merge also NATIVE-540-app-icon

2020-09-15 07:12 UTC, klinzo approved these changes

2020-09-15 08:13 UTC, klinzo requested changes
The integreat logo is missing in the splash screen if I use the commands `start` and `android` to install the app (android emulator). Do I need to use release mode or something?

2020-09-16 11:23 UTC, maxammann commented
Thank you for testing, I fixed this :)

2020-09-16 13:11 UTC, klinzo approved these changes

2020-09-16 13:22 UTC, merged